#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v3
# autospec commit: fae1327
#
Name     : atkmm
Version  : 2.36.3
Release  : 21
URL      : https://download.gnome.org/sources/atkmm/2.36/atkmm-2.36.3.tar.xz
Source0  : https://download.gnome.org/sources/atkmm/2.36/atkmm-2.36.3.tar.xz
Summary  : C++ binding for the ATK accessibility toolkit
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: atkmm-lib = %{version}-%{release}
Requires: atkmm-license = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : doxygen
BuildRequires : pkgconfig(atk)
BuildRequires : pkgconfig(glibmm-2.68)
BuildRequires : pkgconfig(mm-common-libstdc++)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This directory contains files not tracked by a source code control program,
The files can have one of two origins.

%package dev
Summary: dev components for the atkmm package.
Group: Development
Requires: atkmm-lib = %{version}-%{release}
Provides: atkmm-devel = %{version}-%{release}
Requires: atkmm = %{version}-%{release}

%description dev
dev components for the atkmm package.


%package lib
Summary: lib components for the atkmm package.
Group: Libraries
Requires: atkmm-license = %{version}-%{release}

%description lib
lib components for the atkmm package.


%package license
Summary: license components for the atkmm package.
Group: Default

%description license
license components for the atkmm package.


%prep
%setup -q -n atkmm-2.36.3
cd %{_builddir}/atkmm-2.36.3
pushd ..
cp -a atkmm-2.36.3 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1706540869
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
CFLAGS="$CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -march=x86-64-v3 " meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddiravx2
ninja -v -C builddiravx2

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
mkdir -p %{buildroot}/usr/share/package-licenses/atkmm
cp %{_builddir}/atkmm-%{version}/COPYING %{buildroot}/usr/share/package-licenses/atkmm/9a1929f4700d2407c70b507b3b2aaf6226a9543c || :
cp %{_builddir}/atkmm-%{version}/COPYING.tools %{buildroot}/usr/share/package-licenses/atkmm/06877624ea5c77efe3b7e39b0f909eda6e25a4ec || :
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
DESTDIR=%{buildroot} ninja -C builddir install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/atkmm-2.36/proc/m4/convert.m4
/usr/lib64/atkmm-2.36/proc/m4/convert_atk.m4

%files dev
%defattr(-,root,root,-)
/usr/include/atkmm-2.36/atkmm.h
/usr/include/atkmm-2.36/atkmm/action.h
/usr/include/atkmm-2.36/atkmm/component.h
/usr/include/atkmm-2.36/atkmm/document.h
/usr/include/atkmm-2.36/atkmm/editabletext.h
/usr/include/atkmm-2.36/atkmm/hyperlink.h
/usr/include/atkmm-2.36/atkmm/hypertext.h
/usr/include/atkmm-2.36/atkmm/image.h
/usr/include/atkmm-2.36/atkmm/implementor.h
/usr/include/atkmm-2.36/atkmm/init.h
/usr/include/atkmm-2.36/atkmm/noopobject.h
/usr/include/atkmm-2.36/atkmm/object.h
/usr/include/atkmm-2.36/atkmm/objectaccessible.h
/usr/include/atkmm-2.36/atkmm/private/action_p.h
/usr/include/atkmm-2.36/atkmm/private/component_p.h
/usr/include/atkmm-2.36/atkmm/private/document_p.h
/usr/include/atkmm-2.36/atkmm/private/editabletext_p.h
/usr/include/atkmm-2.36/atkmm/private/hyperlink_p.h
/usr/include/atkmm-2.36/atkmm/private/hypertext_p.h
/usr/include/atkmm-2.36/atkmm/private/image_p.h
/usr/include/atkmm-2.36/atkmm/private/implementor_p.h
/usr/include/atkmm-2.36/atkmm/private/noopobject_p.h
/usr/include/atkmm-2.36/atkmm/private/object_p.h
/usr/include/atkmm-2.36/atkmm/private/objectaccessible_p.h
/usr/include/atkmm-2.36/atkmm/private/range_p.h
/usr/include/atkmm-2.36/atkmm/private/relation_p.h
/usr/include/atkmm-2.36/atkmm/private/relationset_p.h
/usr/include/atkmm-2.36/atkmm/private/selection_p.h
/usr/include/atkmm-2.36/atkmm/private/stateset_p.h
/usr/include/atkmm-2.36/atkmm/private/streamablecontent_p.h
/usr/include/atkmm-2.36/atkmm/private/table_p.h
/usr/include/atkmm-2.36/atkmm/private/text_p.h
/usr/include/atkmm-2.36/atkmm/private/value_p.h
/usr/include/atkmm-2.36/atkmm/range.h
/usr/include/atkmm-2.36/atkmm/relation.h
/usr/include/atkmm-2.36/atkmm/relationset.h
/usr/include/atkmm-2.36/atkmm/selection.h
/usr/include/atkmm-2.36/atkmm/stateset.h
/usr/include/atkmm-2.36/atkmm/streamablecontent.h
/usr/include/atkmm-2.36/atkmm/table.h
/usr/include/atkmm-2.36/atkmm/text.h
/usr/include/atkmm-2.36/atkmm/value.h
/usr/include/atkmm-2.36/atkmm/wrap_init.h
/usr/lib64/atkmm-2.36/include/atkmmconfig.h
/usr/lib64/libatkmm-2.36.so
/usr/lib64/pkgconfig/atkmm-2.36.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libatkmm-2.36.so.1.1.0
/usr/lib64/libatkmm-2.36.so.1
/usr/lib64/libatkmm-2.36.so.1.1.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/atkmm/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
/usr/share/package-licenses/atkmm/9a1929f4700d2407c70b507b3b2aaf6226a9543c
