#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : atkmm
Version  : 2.36.2
Release  : 17
URL      : https://download.gnome.org/sources/atkmm/2.36/atkmm-2.36.2.tar.xz
Source0  : https://download.gnome.org/sources/atkmm/2.36/atkmm-2.36.2.tar.xz
Summary  : C++ binding for the ATK accessibility toolkit
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: atkmm-lib = %{version}-%{release}
Requires: atkmm-license = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : doxygen
BuildRequires : pkgconfig(atk)
BuildRequires : pkgconfig(glibmm-2.68)
BuildRequires : pkgconfig(mm-common-libstdc++)

%description
This directory contains files not tracked by a source code control program,
The files can have one of two origins.

%package dev
Summary: dev components for the atkmm package.
Group: Development
Requires: atkmm-lib = %{version}-%{release}
Provides: atkmm-devel = %{version}-%{release}
Requires: atkmm = %{version}-%{release}

%description dev
dev components for the atkmm package.


%package lib
Summary: lib components for the atkmm package.
Group: Libraries
Requires: atkmm-license = %{version}-%{release}

%description lib
lib components for the atkmm package.


%package license
Summary: license components for the atkmm package.
Group: Default

%description license
license components for the atkmm package.


%prep
%setup -q -n atkmm-2.36.2
cd %{_builddir}/atkmm-2.36.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1658328282
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/atkmm
cp %{_builddir}/atkmm-2.36.2/COPYING %{buildroot}/usr/share/package-licenses/atkmm/9a1929f4700d2407c70b507b3b2aaf6226a9543c
cp %{_builddir}/atkmm-2.36.2/COPYING.tools %{buildroot}/usr/share/package-licenses/atkmm/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)
/usr/lib64/atkmm-2.36/proc/m4/convert.m4
/usr/lib64/atkmm-2.36/proc/m4/convert_atk.m4

%files dev
%defattr(-,root,root,-)
/usr/include/atkmm-2.36/atkmm.h
/usr/include/atkmm-2.36/atkmm/action.h
/usr/include/atkmm-2.36/atkmm/component.h
/usr/include/atkmm-2.36/atkmm/document.h
/usr/include/atkmm-2.36/atkmm/editabletext.h
/usr/include/atkmm-2.36/atkmm/hyperlink.h
/usr/include/atkmm-2.36/atkmm/hypertext.h
/usr/include/atkmm-2.36/atkmm/image.h
/usr/include/atkmm-2.36/atkmm/implementor.h
/usr/include/atkmm-2.36/atkmm/init.h
/usr/include/atkmm-2.36/atkmm/noopobject.h
/usr/include/atkmm-2.36/atkmm/object.h
/usr/include/atkmm-2.36/atkmm/objectaccessible.h
/usr/include/atkmm-2.36/atkmm/private/action_p.h
/usr/include/atkmm-2.36/atkmm/private/component_p.h
/usr/include/atkmm-2.36/atkmm/private/document_p.h
/usr/include/atkmm-2.36/atkmm/private/editabletext_p.h
/usr/include/atkmm-2.36/atkmm/private/hyperlink_p.h
/usr/include/atkmm-2.36/atkmm/private/hypertext_p.h
/usr/include/atkmm-2.36/atkmm/private/image_p.h
/usr/include/atkmm-2.36/atkmm/private/implementor_p.h
/usr/include/atkmm-2.36/atkmm/private/noopobject_p.h
/usr/include/atkmm-2.36/atkmm/private/object_p.h
/usr/include/atkmm-2.36/atkmm/private/objectaccessible_p.h
/usr/include/atkmm-2.36/atkmm/private/range_p.h
/usr/include/atkmm-2.36/atkmm/private/relation_p.h
/usr/include/atkmm-2.36/atkmm/private/relationset_p.h
/usr/include/atkmm-2.36/atkmm/private/selection_p.h
/usr/include/atkmm-2.36/atkmm/private/stateset_p.h
/usr/include/atkmm-2.36/atkmm/private/streamablecontent_p.h
/usr/include/atkmm-2.36/atkmm/private/table_p.h
/usr/include/atkmm-2.36/atkmm/private/text_p.h
/usr/include/atkmm-2.36/atkmm/private/value_p.h
/usr/include/atkmm-2.36/atkmm/range.h
/usr/include/atkmm-2.36/atkmm/relation.h
/usr/include/atkmm-2.36/atkmm/relationset.h
/usr/include/atkmm-2.36/atkmm/selection.h
/usr/include/atkmm-2.36/atkmm/stateset.h
/usr/include/atkmm-2.36/atkmm/streamablecontent.h
/usr/include/atkmm-2.36/atkmm/table.h
/usr/include/atkmm-2.36/atkmm/text.h
/usr/include/atkmm-2.36/atkmm/value.h
/usr/include/atkmm-2.36/atkmm/wrap_init.h
/usr/lib64/atkmm-2.36/include/atkmmconfig.h
/usr/lib64/libatkmm-2.36.so
/usr/lib64/pkgconfig/atkmm-2.36.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libatkmm-2.36.so.1
/usr/lib64/libatkmm-2.36.so.1.1.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/atkmm/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
/usr/share/package-licenses/atkmm/9a1929f4700d2407c70b507b3b2aaf6226a9543c
